name: Deployment-reusable-workflow
on: 
  workflow_call:

jobs:
    reuse-deply:
        environment: 
          name: development
          url: http://${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}:31526
        needs: docker
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.28.15' # default is latest stable
              id: install

            - name: Setup Kubeconfig context
              uses: azure/k8s-set-context@v5
              with:
                 method: kubeconfig
                 kubeconfig: ${{ secrets.KUBECONFIG }} 

 #           - name: save public ip for ingress
 #             id: get_ip
 #             run: |
 #                echo = "INGRESS_IP=$(curl ifconfig.me)" >> "$GITHUB_ENV"
#                IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')


            - name : Replace tokens
              uses: cschleiden/replace-tokens@v1
              with:
                  tokenPrefix: '${'
                  tokenSuffix: '}'
                  files: '["kubernetes/development/*.yaml"]'
              env:
                 NAMESPACE: ${{ vars.NAMESPACE }}
                 REPLICAS: ${{ vars.REPLICAS }}
                 K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}   
                 INGRESS_IP: '13.71.2.57'  

            - name: create mongo secret
              run: |
                 kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds  \
                 --from-literal=username=${{ vars.MONGO_USERNAME }} \
                 --from-literal=password=${{ secrets.MONGO_PASS }} \
                 --from-literal=uri='mongodb://mongodb:27017/mydb' \
                 --dry-run=client -o yaml | kubectl apply -f -
                 
            - name : Deploy to Developmet
              run: |
                 kubectl apply -f kubernetes/development/ -n ${{ vars.NAMESPACE }}

            - name: set app Ingress host URL
              id: set-ingress-host-url
              run: |
                 url=
                 echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ing -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"
   