name: NPM Action
description: A custom action to run npm commands in a GitHub Actions workflow.
inputs:
  path-to-folder:
    description: 'The path to the folder where npm commands should be executed.'
    required: true
runs:
  using: "composite"
  steps:
      - name: cache node dependencies
        uses: actions/cache@v3
        with:
            path: ${{ inputs.path-to-folder }}
            key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install
        shell: bash