on: [workflow_dispatch,push]
name: CI Workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
    unit-test:
        strategy:
            matrix:
                nodejs-version: [ 20]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        services:
            mongo-db:
                image: siddharth67/mongo-db:non-prod
                ports:
                    - 27017:27017
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name : setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.nodejs-version }}

            - name: cache node dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install Dependencies
              run: npm install

            - name: Run Unit Tests
              id: unit_test
              run: npm test

            - name: Archive test results
              if: always()
              uses: actions/upload-artifact@v5
              with:
                  name: test-results
                  path: test-results.xml
    
    code-coverage:
        runs-on: ubuntu-latest
        container:
            image: node:18
        services:
            mongo-db:
                image: siddharth67/mongo-db:non-prod
                options:
                  --name mongo
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # - name : setup Node
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'

            - name: cache node dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install Dependencies
              run: npm install

            - name: Run Code Coverage
              run: npm run coverage
              continue-on-error: true

            - name: Upload Code Coverage-Report
              uses: actions/upload-artifact@v5
              if: always()
              with:
                  name: code-coverage-report
                  path: coverage
                  retention-days: 5

    reports:
        name: Gather Reports
        runs-on: ubuntu-latest
        needs: [unit-test, code-coverage]
        steps:
            - name: Download Unit Testing Reports
              uses: actions/download-artifact@v5
              with:
                  name: test-results
  
            - name: Download Unit Testing Reports
              uses: actions/download-artifact@v5
              with:
                  name: code-coverage-report

            - name: Merge all reports
              run: |
               ls -ltr
               mkdir reports-${{ github.sha }}
               mv test-results.xml reports-${{ github.sha }}/
               mv cobertura-coverage.xml reports-${{ github.sha }}/
               ls -ltr reports-${{ github.sha }}

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Upload Reports to Azure Files
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                    az storage file upload --share-name ${{ vars.AZURE_FILE_SHARE_NAME }} \
                    --source reports-${{ github.sha }}/test-results.xml \
                    --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
    
    docker:
        name: containerizaton
        runs-on: ubuntu-latest
        needs: reports
        permissions:
            packages: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v4
              with:
                  username: ${{ vars.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
              
            - name: Login to GHCR
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push to cotainer registry
              uses: docker/build-push-action@v4
              with:
                  context: .   #going to search for Dockerfile in the root directory
                  push: true
                  tags: |
                     ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
                    # ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    dev-deploy:
        needs: docker
        uses: ./.github/workflows/reusable-workflow.yaml
        secrets:
            k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
            mongodb-password: ${{ secrets.MONGO_PASS}}
        with:
            mongodb-uri: ${{ vars.MONGO_URI }}
            k8s-manifest-path: 'kubernetes/development/'
            environment: 'development'  

        
    dev-integration-testing:
              name: Dev Integation Testing
              needs: dev-deploy
              runs-on: ubuntu-latest
              steps:
                - name: Test API Endpoint
                  env:
                    url: ${{ needs.dev-deploy.outputs.application-url }}
                  run: |
                       echo $url
                       echo "Running integration tests against dev environment"
                       echo "----------------------------------------------"
                       curl http://$url:31526/live -s -k | jq -r .status | grep -i live 

              
    prod-deploy:
        name: Deploy to Prod Environment
        needs: dev-integration-testing
        uses: ./.github/workflows/reusable-workflow.yaml
        secrets:
            k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
            mongodb-password: ${{ secrets.MONGO_PASS}}
        with:
            mongodb-uri: ${{ vars.MONGO_URI }}
            k8s-manifest-path: 'kubernetes/production/'
            environment: 'production'
            
    prod-integration-testing:
              name: Prod Integation Testingg
              needs: prod-deploy
              runs-on: ubuntu-latest
              steps:
                - name: Test API Endpoint
                  env:
                    url: ${{ needs.prod-deploy.outputs.application-url }}
                  run: |
                       echo $url
                       echo "Running integration tests against production environment"
                       echo "----------------------------------------------"
                       curl http://$url:31526/live -s -k | jq -r .status | grep -i live 

            
                


            

          



            
              


