on: [workflow_dispatch,push]
name: CI Workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
    unit-test:
        strategy:
            matrix:
                nodejs-version: [ 20]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        services:
            mongo-db:
                image: siddharth67/mongo-db:non-prod
                ports:
                    - 27017:27017
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name : setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.nodejs-version }}

            - name: cache node dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install Dependencies
              run: npm install

            - name: Run Unit Tests
              id: unit_test
              run: npm test

            - name: Archive test results
              if: always()
              uses: actions/upload-artifact@v5
              with:
                  name: test-results
                  path: test-results.xml
    
    code-coverage:
        runs-on: ubuntu-latest
        container:
            image: node:18
        services:
            mongo-db:
                image: siddharth67/mongo-db:non-prod
                options:
                  --name mongo
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASS }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # - name : setup Node
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '18'

            - name: cache node dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Install Dependencies
              run: npm install

            - name: Run Code Coverage
              run: npm run coverage
              continue-on-error: true

            - name: Upload Code Coverage-Report
              uses: actions/upload-artifact@v5
              if: always()
              with:
                  name: code-coverage-report
                  path: coverage
                  retention-days: 5
    
    docker:
        name: containerizaton
        runs-on: ubuntu-latest
        needs: [unit-test, code-coverage]
        permissions:
            packages: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to DockerHub
              uses: docker/login-action@v4
              with:
                  username: ${{ vars.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
              
            - name: Login to GHCR
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push to cotainer registry
              uses: docker/build-push-action@v4
              with:
                  context: .   #going to search for Dockerfile in the root directory
                  push: true
                  tags: |
                     ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
                    # ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}

    dev-deploy:
        name: Deploy to Dev Environment
        runs-on: ubuntu-latest
        environment: 
          name: development
          url: http://${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}:31526
        needs: docker
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.28.15' # default is latest stable
              id: install

            - name: Setup Kubeconfig context
              uses: azure/k8s-set-context@v5
              with:
                 method: kubeconfig
                 kubeconfig: ${{ secrets.KUBECONFIG }} 

 #           - name: save public ip for ingress
 #             id: get_ip
 #             run: |
 #                echo = "INGRESS_IP=$(curl ifconfig.me)" >> "$GITHUB_ENV"
#                IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')


            - name : Replace tokens
              uses: cschleiden/replace-tokens@v1
              with:
                  tokenPrefix: '${'
                  tokenSuffix: '}'
                  files: '["kubernetes/development/*.yaml"]'
              env:
                 NAMESPACE: ${{ vars.NAMESPACE }}
                 REPLICAS: ${{ vars.REPLICAS }}
                 K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}   
                 INGRESS_IP: '13.71.2.57'  

            - name: create mongo secret
              run: |
                 kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds  \
                 --from-literal=username=${{ vars.MONGO_USERNAME }} \
                 --from-literal=password=${{ secrets.MONGO_PASS }} \
                 --from-literal=uri='mongodb://mongodb:27017/mydb' \
                 --dry-run=client -o yaml | kubectl apply -f -
                 
            - name : Deploy to Developmet
              run: |
                 kubectl apply -f kubernetes/development/ -n ${{ vars.NAMESPACE }}

            - name: set app Ingress host URL
              id: set-ingress-host-url
              run: |
                 url=
                 echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ing -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"

    dev-integration-testing:
              name: Dev Integation Testingg
              needs: dev-deploy
              runs-on: ubuntu-latest
              steps:
                - name: Test API Endpoint
                  env:
                    url: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
                  run: |
                       echo $url
                       echo "Running integration tests against dev environment"
                       echo "----------------------------------------------"
                       curl http://$url:31526/live -s -k | jq -r .status | grep -i live 

              
    prod-deploy:
        name: Deploy to Prod Environment
        runs-on: ubuntu-latest
        environment: 
          name: production
          url: http://${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}:31526
        needs: dev-integration-testing
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Kubectl
              uses: azure/setup-kubectl@v4
              with:
                version: 'v1.28.15' # default is latest stable
              id: install

            - name: Setup Kubeconfig context
              uses: azure/k8s-set-context@v5
              with:
                 method: kubeconfig
                 kubeconfig: ${{ secrets.KUBECONFIG }} 

 #           - name: save public ip for ingress
 #             id: get_ip
 #             run: |
 #                echo = "INGRESS_IP=$(curl ifconfig.me)" >> "$GITHUB_ENV"
#                IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')


            - name : Replace tokens
              uses: cschleiden/replace-tokens@v1
              with:
                  tokenPrefix: '${'
                  tokenSuffix: '}'
                  files: '["kubernetes/production/*.yaml"]'
              env:
                 NAMESPACE: ${{ vars.NAMESPACE }}
                 REPLICAS: ${{ vars.REPLICAS }}
                 K8S_IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}   
                 INGRESS_IP: '13.71.2.57'  

            - name: create mongo secret
              run: |
                 kubectl create ns ${{ vars.NAMESPACE }}
                 kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds  \
                 --from-literal=username=${{ vars.MONGO_USERNAME }} \
                 --from-literal=password=${{ secrets.MONGO_PASS }} \
                 --from-literal=uri='mongodb://mongodb:27017/mydb' \
                 --dry-run=client -o yaml | kubectl apply -f -
                 
            - name : Deploy to Developmet
              run: |
                 kubectl apply -f kubernetes/production/ -n ${{ vars.NAMESPACE }}

            - name: set app Ingress host URL
              id: set-ingress-host-url
              run: |
                 url=
                 echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ing -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"

    prod-integration-testing:
              name: Prod Integation Testingg
              needs: prod-deploy
              runs-on: ubuntu-latest
              steps:
                - name: Test API Endpoint
                  env:
                    url: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL }}
                  run: |
                       echo $url
                       echo "Running integration tests against production environment"
                       echo "----------------------------------------------"
                       curl http://$url:31526/live -s -k | jq -r .status | grep -i live 

            
                


            

          



            
              


